# -*- coding: utf-8 -*-
"""colab code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdZYJil1KNdALf84z7lD4EYZSVG2VUSW
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import joblib

data = pd.DataFrame({'cgpa': [6.5, 7.0, 8.2, 6.9, 7.5, 8.0, 5.5], 'iq': [12, 110, 130, 105, 115, 125,100], 'placed': [1, 1, 1, 0, 1, 1, 0]})

from sklearn.linear_model import LogisticRegression # Import LogisticRegression
X=data[['cgpa', 'iq']]
y=data['placed']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)
model=LogisticRegression()
model.fit(X_train,y_train)

import joblib
joblib.dump(model, 'placement_model.pkl')

import joblib
joblib.dump(model, 'placement_model.pkl')